In [2]:
import numpy as np

In [3]:
n1 = np.array([2, 3, 4, 5, 6])
print(n1 * 2)

[ 4  6  8 10 12]


In [4]:
n2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b
add

array([5, 7, 9])

In [6]:
c = np.array([[2, 3], [5, 4]])
d = np.array([[4, 3], [6, 5]])
c * d

array([[ 8,  9],
       [30, 20]])

In [7]:
dot_prod = np.dot(c, d)
dot_prod

array([[26, 21],
       [44, 35]])

In [8]:
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.min(n2))
print(np.max(n2))
print(np.median(n2))
print(np.std(n2))
print(np.var(n2))
print(np.argmax(n2))
print(np.argmin(n2))

120
1307674368000
8.0
1
15
8.0
4.320493798938574
18.666666666666668
14
0


In [10]:
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
print(np.sum(n2, axis = 1))
print(np.sum(n2, axis = 0))

[15 40 65]
[18 21 24 27 30]


In [12]:
n3 = np.arange(0, 36)
n3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [13]:
n4 = np.random.randint(0, 200, (5, 6))
n4

array([[ 86, 125,   1,  95,  54, 186],
       [ 14,  56,  24,  54, 166,  28],
       [125,  51, 174,  31, 118,  35],
       [ 50, 115, 174, 191,  17,  92],
       [110, 118, 164,  42, 118,  27]])

In [14]:
n5 = np.random.rand(5, 6)
n5

array([[0.03200795, 0.23939093, 0.1886717 , 0.91295629, 0.46866831,
        0.13329312],
       [0.67525693, 0.74023906, 0.86835282, 0.60335733, 0.09338676,
        0.96443658],
       [0.34798304, 0.9542291 , 0.78361816, 0.07284046, 0.8953714 ,
        0.23595042],
       [0.48427831, 0.22334552, 0.5420791 , 0.1754156 , 0.59943113,
        0.59844808],
       [0.00535057, 0.44885375, 0.71126054, 0.35416588, 0.16848457,
        0.0824199 ]])

In [15]:
n6 = np.zeros((5, 6))
n6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
n7 = np.ones((5, 6))
n7

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
n8 = np.eye(5)
n8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
n3_reshaped = n3.reshape(6, 6)
n3_reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [19]:
n3_transposed = np.transpose(n3_reshaped)
n3_transposed

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[2 : 6]

array([3, 4, 5, 6])

In [21]:
n3_reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
n3_reshaped[1 : 3, 1 : 4]

array([[ 7,  8,  9],
       [13, 14, 15]])

In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2, 3], [4, 5, 6]])
arr_hstacked = np.hstack((x, y))
arr_hstacked

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [24]:
arr_vstacked = np.vstack((x, y))
arr_vstacked

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
print(n2)
print(n2 + 1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]


In [26]:
z = np.array([1, 2, 3, 4, 5])
print(n2 + z)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]]


In [27]:
np.square(z)

array([ 1,  4,  9, 16, 25])

In [28]:
data = np.array([3, 2, 1, 6, 4, 9, 8, 7, 2, 5, 10, 3])
np.sort(data)

array([ 1,  2,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.unique(data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.where(data == 2)

(array([1, 8]),)

Determinent

In [31]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

Inverse of matrix

In [32]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

* 3x + 4y + z = 7
* 2x + 2y + 2z = 14
* 4x + y + z = 21

In [33]:
A = np.array([[3,4,1] , [2,2,2] , [4,1,1]])
print(A)
X = np.array([['x'] , ['y'] , ['z']])
print(X)
Z = np.array([[7] , [14] , [21]])
print(Z)

[[3 4 1]
 [2 2 2]
 [4 1 1]]
[['x']
 ['y']
 ['z']]
[[ 7]
 [14]
 [21]]


In [34]:
#A.X = Z
#X = invA.Z

invA = np.linalg.inv(A)
X = np.dot(invA , Z)
print(X)

[[ 4.66666667]
 [-3.11111111]
 [ 5.44444444]]


In [35]:
np.dot(A,X)

array([[ 7.],
       [14.],
       [21.]])

In [36]:
arr2 = np.random.rand(3, 5)
arr2

array([[0.68891796, 0.63756822, 0.23917254, 0.83987553, 0.59257025],
       [0.27473934, 0.49767848, 0.12057037, 0.10823271, 0.2082834 ],
       [0.46604113, 0.27897853, 0.27971077, 0.34575043, 0.65192311]])